version: "3"

services:
  db:
    image: "postgres:14.2"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ps_user
      - POSTGRES_PASSWORD=ps_password
      - POSTGRES_DB=patients_service