openapi: 3.0.3

info:
  title: Patient Service
  description: Stores patient information
  version: 1.0.0
paths:
  /patients:
    post:
      summary: create a patient in the system
      requestBody:
        $ref: '#/components/requestBodies/NewPatient'
      responses:
        201:
          $ref: '#/components/schemas/Patient'
        400:
          $ref: '#/components/responses/ValidationError'
        500:
          description: try later or contact us at support@quiquedev.info
  /patients/{id}:
    get:
      summary: get a patient
      parameters:
        - in: path
          required: true
          name: id
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        200:
          $ref: '#/components/schemas/Patient'
        404:
          description: patient with given id not found
        500:
          description: try later or contact us at support@quiquedev.info
components:
  requestBodies:
    NewPatient:
      description: patient information
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - surname
              - passportNumber
            properties:
              name:
                $ref: '#/components/schemas/Name'
              surname:
                $ref: '#/components/schemas/Surname'
              passportNumber:
                $ref: '#/components/schemas/PassportNumber'
  responses:
    ValidationError:
      description: patient information is not valid
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: body request is not valid
              errors:
                type: array
                items:
                  type: string
                  example: name cannot be blank
  schemas:
    Patient:
      type: object
      required:
        - id
        - passportNumber
        - name
        - surname
        - createdAt
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/Name'
        surname:
          $ref: '#/components/schemas/Surname'
        passportNumber:
          $ref: '#/components/schemas/PassportNumber'
        createdAt:
          $ref: '#/components/schemas/DateTime'
    Name:
      type: string
      maxLength: 50
      minLength: 1
      example: Robert
    Surname:
      type: string
      maxLength: 150
      minLength: 1
      example: Mareq
    PassportNumber:
      description: unique for each patient
      type: string
      maxLength: 10
      minLength: 10
      example: 76548353RM
    Id:
      description: internal unique id for each patient
      type: string
      format: uuid
      minLength: 35
      maxLength: 35
      example: 23e4567-e89b-12d3-a456-426614174000
    DateTime:
      type: string
      format: date-time
      example: 2021-07-21T17:32:28Z
