###
POST http://localhost:8080/patients
Content-Type: application/json

{
  "name": "enrique",
  "surname": "benitez",
  "passportNumber": "uuuuuu4uusu"
}

###
GET http://localhost:8080/patients/5f9cc603-73ad-45e7-8302-e1aed2fb6106


